/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rasn_runtime_constants.h"

namespace dsn { namespace rasn { namespace rpc {

const rasn_runtimeConstants g_rasn_runtime_constants;

rasn_runtimeConstants::rasn_runtimeConstants() {
  RASN_RUNTIME_WIRE_VERSION = 1;

  RASN_RUNTIME_MIN_COMPATIBLE_VERSION = 1;

}

}}} // namespace
