/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rasn_runtime_CONSTANTS_H
#define rasn_runtime_CONSTANTS_H

#include "rasn_runtime_types.h"

namespace dsn { namespace rasn { namespace rpc {

class rasn_runtimeConstants {
 public:
  rasn_runtimeConstants();

  int32_t RASN_RUNTIME_WIRE_VERSION;
  int32_t RASN_RUNTIME_MIN_COMPATIBLE_VERSION;
};

extern const rasn_runtimeConstants g_rasn_runtime_constants;

}}} // namespace

#endif
